"""2026-10-09 공식 홈페이지 상단 메뉴에서 직접 확인한 요금제 목록.

목록 주소 확인과 상품 수집 완료는 다르다. 동적 페이지는 별도 API 파서가 필요하다.
"""
OFFICIAL_PLAN_LIST_URLS={
    '쉐이크모바일':'https://shakemobile.co.kr/M2Mobile/Set3G',
    '플래시모바일':'https://olleh.flashmobile.kr/html_k/pay_main.html',
    '친구모바일':'https://chingumobile.com/ko/plans/select/postpaid',
    '아정당모바일':'https://www.ajdmobile.co.kr/rate_plan.do',
    '이음모바일':'https://eummobile.co.kr/rate',
    '에르엘':'https://www.erel.co.kr/usim/entry-soc',
    'SK 7mobile':'https://www.sk7mobile.com/prod/data/callingPlanList.do?refCode=USIM',
    'KB리브모바일':'https://m.liivm.com/rateplan/plans/products',
    '우리WON모바일':'https://www.wooriwonmobile.com/rate-plan/list',
    '핀다이렉트':'https://www.pindirectshop.com/deal-list',
    '위너스텔(WELL)':'https://www.idowell.co.kr/rate_plan.do',
    '에스원 안심모바일':'http://www.s1mobile.co.kr/home/plan/rateList.do?rateDv=U',
    '밸류컴':'https://www.valuecomm.co.kr/bbs/board.php?bo_table=pricList&sca=후불',
    '코인샷 모바일':'https://mobile.coinshot.org/ko/mobilePlan',
    '알비레오':'https://www.albireomobile.com/plan',
    '아이디스파워텔':'https://idispowertel.com/html/dh/powertalk3_3',
    '드림라인 모바일':'https://dreammobile.kr/view/service/plans.aspx',
    '퍼스트 모바일':'https://www.firstmobile.co.kr/bbs/board.php?bo_table=pricList&sca=후불&sca2=KT',
    '더원모바일':'https://www.theonem.co.kr/view/plan/phone_plan.aspx',
    '한국E텔레콤':'https://www.koretel.co.kr/view/plan/phone_plan.aspx',
    'MONA':'https://mobilemona.co.kr/view/plan/rate_plan.aspx',
    'GME모바일':'https://www.gmemobile.com/view/plan/phone_plan.aspx',
    '아이즈모바일':'https://eyes.co.kr/payplan/all_plan/',
    '조이텔':'https://joytel.co.kr/rate_plan.do',
    '도시락모바일':'https://www.dosirakmobile.com/rate_plan.do',
    'KT스카이라이프':'https://www.skylife.co.kr/product/mobile/all',
    '한패스모바일':'https://www.hanpassmobile.co.kr/rate_plan.do',
    'KCTV모바일':'https://kctvm.com/rate_plan.do',
    '시월모바일':'https://www.siwolmobile.com/rate_plan.do',
    '고고모바일(고고팩토리)':'https://www.gogomobile.co.kr/onlineplan',
    'KT M모바일':'https://www.ktmmobile.com/rate/rateList.do',
    '이야기모바일':'https://www.eyagi.co.kr/shop/plan/list.php?tag=pick',
    '찬스모바일':'https://chancemobile.co.kr/view/plan/phone_plan.aspx',
    '온국민폰':'https://xn--3e0b39yfuhjlo.kr/rate_plan.do',
}
